"""empty message

Revision ID: 195ed5e84555
Revises: 4eaadac1b6cb
Create Date: 2023-09-13 21:26:45.519156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195ed5e84555'
down_revision = '4eaadac1b6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_population_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.create_unique_constraint('planet_population_key', ['population'])

    # ### end Alembic commands ###
