"""empty message

Revision ID: 38a295ab6087
Revises: b2e967b1fb52
Create Date: 2023-08-18 23:15:37.507911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a295ab6087'
down_revision = 'b2e967b1fb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_gender_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_gender_key', ['gender'])

    # ### end Alembic commands ###
