"""empty message

Revision ID: d35f98a997ca
Revises: 65be2c77cc03
Create Date: 2023-08-25 22:56:40.055060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35f98a997ca'
down_revision = '65be2c77cc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('people_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planet_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vehicle_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('vehicle_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planet_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('people_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
