"""empty message

Revision ID: e870d8d295f9
Revises: 
Create Date: 2023-08-23 22:21:21.802318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e870d8d295f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('birth_year', sa.String(length=80), nullable=False),
    sa.Column('height', sa.String(length=80), nullable=False),
    sa.Column('mass', sa.String(length=80), nullable=False),
    sa.Column('hair_color', sa.String(length=80), nullable=False),
    sa.Column('skin_color', sa.String(length=80), nullable=False),
    sa.Column('eye_color', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('image')
    )
    op.create_table('planet',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('population', sa.String(length=15), nullable=False),
    sa.Column('terrain', sa.String(length=80), nullable=False),
    sa.Column('climate', sa.String(length=80), nullable=False),
    sa.Column('surface_water', sa.String(length=80), nullable=False),
    sa.Column('rotation_period', sa.String(length=80), nullable=False),
    sa.Column('orbital_period', sa.String(length=80), nullable=False),
    sa.Column('diameter', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('population')
    )
    op.create_table('vehicle',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=15), nullable=False),
    sa.Column('vehicle_class', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.String(length=80), nullable=False),
    sa.Column('cost_in_credits', sa.String(length=80), nullable=False),
    sa.Column('length', sa.String(length=80), nullable=False),
    sa.Column('passengers', sa.String(length=80), nullable=False),
    sa.Column('cargo_capacity', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('model')
    )
    op.create_table('favorites',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('people_uid', sa.Integer(), nullable=False),
    sa.Column('planet_uid', sa.Integer(), nullable=False),
    sa.Column('vehicle_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_uid'], ['people.uid'], ),
    sa.ForeignKeyConstraint(['planet_uid'], ['planet.uid'], ),
    sa.ForeignKeyConstraint(['vehicle_uid'], ['vehicle.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('vehicle')
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
